//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazSistema
{
    using System;
    using System.Collections.Generic;
    
    public partial class archivos
    {
        public int id { get; set; }
        public string Descripcion { get; set; }
        public string Ruta { get; set; }
        public System.DateTime UltimaVez { get; set; }
        public bool ExisteEnDVB { get; set; }
        public System.DateTime caducidad { get; set; }
        public System.DateTime Duracion { get; set; }
        public int clasificacion { get; set; }
        public int idioma { get; set; }
        public int subtitulos { get; set; }
        public int formato { get; set; }
        public int tipoarchivo { get; set; }
        public System.DateTime InicioVig { get; set; }
    }
}
