//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazSistema
{
    using System;
    using System.Collections.Generic;
    
    public partial class can_parametrosinicio
    {
        public long IdParametrosInicio { get; set; }
        public Nullable<long> TiempoUltimaVez { get; set; }
        public Nullable<bool> PlaySobrePlay { get; set; }
        public string AnilloRedValido { get; set; }
        public string CarpetaFTP { get; set; }
        public string RutaHTTP { get; set; }
        public Nullable<long> IntervaloResultado { get; set; }
        public Nullable<long> TiempoActivaSec { get; set; }
        public string RutaDVB { get; set; }
        public Nullable<bool> SincronizaSubida { get; set; }
        public Nullable<bool> SincronizaBajada { get; set; }
        public Nullable<bool> AlwaysOnTop { get; set; }
        public string HoraInicial { get; set; }
        public string HoraFinal { get; set; }
        public string Password { get; set; }
        public string Autobus { get; set; }
        public Nullable<long> Region { get; set; }
        public Nullable<long> Marca { get; set; }
        public string Zona { get; set; }
        public Nullable<long> IDGrupo { get; set; }
        public Nullable<bool> TecladoActivo { get; set; }
        public string CodigoSalir { get; set; }
        public Nullable<long> CodigoReinicio { get; set; }
        public Nullable<long> CodigoBuscaSecuencia { get; set; }
        public Nullable<long> CodigoEjecutaDVB { get; set; }
        public Nullable<long> CodigoMensajes { get; set; }
        public Nullable<long> CodigoCargaUSB { get; set; }
        public Nullable<long> CodigoPautas { get; set; }
        public Nullable<long> PautaAutomatica { get; set; }
        public string RemoteHost { get; set; }
        public Nullable<long> RemotePort { get; set; }
        public Nullable<long> MargenGPS { get; set; }
        public Nullable<long> TiempoGPS { get; set; }
        public Nullable<long> PuertoSerial { get; set; }
        public string ConfigSerial { get; set; }
        public string MemoriaSIM { get; set; }
        public string SIMCentral { get; set; }
        public Nullable<bool> CONTROLPROPIO { get; set; }
        public string RemoteServerName { get; set; }
        public string RemoteServerDB { get; set; }
        public string RemoteServerUser { get; set; }
        public string RemoteServerPass { get; set; }
        public Nullable<bool> ValidarCveCondSec { get; set; }
        public Nullable<bool> HabilitarCintillo { get; set; }
        public string MensajeInicial { get; set; }
        public Nullable<long> VueltasMensaje { get; set; }
        public Nullable<long> AltoCintillo { get; set; }
        public string ColorFuente { get; set; }
        public Nullable<long> TamanoFuente { get; set; }
        public string ColorFondo { get; set; }
        public Nullable<long> Velocidad { get; set; }
        public string PosicionMarquee { get; set; }
        public Nullable<bool> HabilitarPI { get; set; }
        public Nullable<long> PantallaSerial { get; set; }
        public string ConfigPantallaSerial { get; set; }
        public Nullable<long> PosicionBuzzer { get; set; }
        public Nullable<bool> PantallaTouch { get; set; }
        public Nullable<bool> EncCAN { get; set; }
        public Nullable<bool> EncVMD { get; set; }
        public Nullable<bool> EncCondusat { get; set; }
        public Nullable<bool> VMD { get; set; }
        public Nullable<bool> CAN { get; set; }
        public Nullable<bool> SIIAB_POI { get; set; }//Powered byToto
        public Nullable<bool> CONDUSAT { get; set; }
        public Nullable<bool> MensajesConductor { get; set; }
        public Nullable<long> InicioViaje { get; set; }
        public Nullable<long> FinViaje { get; set; }
        public Nullable<long> CambioManos { get; set; }
        public Nullable<long> Sincronizar { get; set; }
        public Nullable<double> MetaRendimiento { get; set; }
        public Nullable<long> SegsGraba { get; set; }
        public Nullable<long> SegsMuestra { get; set; }
        public string Servicio { get; set; }
        public string CnStrServer { get; set; }
        public Nullable<long> LedVerde { get; set; }
        public Nullable<long> LedAmarillo { get; set; }
        public Nullable<long> LedRojo { get; set; }
        public string LedX { get; set; }
        public Nullable<double> MaxVel { get; set; }
        public Nullable<long> IDDireccion { get; set; }
        public Nullable<long> IDRegionOperativa { get; set; }
        public Nullable<long> DatosCAN { get; set; }
        public string NombreTipoMetaCAN { get; set; }
        public string NombreRegionOperCAN { get; set; }
        public Nullable<long> ViajePrueba { get; set; }
        public string IDWIFI { get; set; }
        public Nullable<double> ExcesosVel { get; set; }
        public Nullable<double> ExcesosRPMs { get; set; }
        public Nullable<long> SegsEsperaApp { get; set; }
        public Nullable<bool> LogSincronizacionBien { get; set; }
        public Nullable<bool> LogSincronizacionMal { get; set; }
        public Nullable<long> MonitorGPS { get; set; }
        public string RutaDiscoMBR { get; set; }
        public Nullable<bool> SincronizaEnAlterno { get; set; }
        public Nullable<bool> TablasPorBus { get; set; }
        public string CarpetaVideos { get; set; }
        public Nullable<bool> SIA { get; set; }
        public Nullable<bool> ValidaOperadorSIA { get; set; }
        public Nullable<bool> UsoMetrobus { get; set; }
        public Nullable<bool> ValidaVolumen { get; set; }
        public long tmrAlerta { get; set; }
        public Nullable<bool> BotonPanico { get; set; }
        public Nullable<bool> BotonTachuela { get; set; }
        public Nullable<bool> BotonOff { get; set; }
        public long tmrProtector { get; set; }
        public long tmrSegVMDSIA { get; set; }
        public long tmrSegCANSIA { get; set; }
        public string horaInicioModoNocturno { get; set; }
        public string horaFinModoNocturno { get; set; }
        public string MacAddress { get; set; }
        public bool ADOGPS { get; set; }
        public byte ReinicioTerminal { get; set; }
        public Nullable<long> HrsReinicioTerminal { get; set; }
        public Nullable<long> MinApagadoSincronizacion { get; set; }
        public byte ReinicioCM { get; set; }
        public byte ProtectorDiurno { get; set; }
        public byte ProtectorNocturno { get; set; }
        public Nullable<bool> MiniSIA { get; set; }
        public Nullable<int> ReinicioTiempoTerminal { get; set; }
        public bool PLAT { get; set; }
        public bool TELEMATICS { get; set; }
        public string IdLAN { get; set; }
        public bool SPOTS { get; set; }
    }
}
