//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazSistema
{
    using System;
    using System.Collections.Generic;
    
    public partial class can_viajes
    {
        public int idviaje { get; set; }
        public System.DateTime fecha { get; set; }
        public string origen { get; set; }
        public string destino { get; set; }
    }
}
