//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazSistema
{
    using System;
    using System.Collections.Generic;
    
    public partial class can_poblaciones
    {
        public long idpob { get; set; }
        public string despob { get; set; }
        public double latitud { get; set; }
        public string ns { get; set; }
        public double longitud { get; set; }
        public string we { get; set; }
        public long IDTIPOPUNTO { get; set; }
        public long IDRegion { get; set; }
        public Nullable<long> IDSeccion { get; set; }
        public string CVEPOB { get; set; }
        public Nullable<bool> Nuevo { get; set; }
        public Nullable<double> LatMax { get; set; }
        public Nullable<double> LatMin { get; set; }
        public Nullable<double> LonMax { get; set; }
        public Nullable<double> LonMin { get; set; }
    }
}
