//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazSistema
{
    using System;
    using System.Collections.Generic;
    
    public partial class can_catmetasregionros
    {
        public string Clasificacion { get; set; }
        public string Tipo { get; set; }
        public Nullable<float> Consejo { get; set; }
        public Nullable<float> Odometro { get; set; }
        public string Mes { get; set; }
        public Nullable<int> Year { get; set; }
        public string Region { get; set; }
        public long id { get; set; }
    }
}
