//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazSistema
{
    using System;
    using System.Collections.Generic;
    
    public partial class can_referenciaregion
    {
        public long IdRegion { get; set; }
        public string Region { get; set; }
        public string Marca { get; set; }
        public string Zona { get; set; }
        public string IdGrupo { get; set; }
        public string IdDireccion { get; set; }
        public string IdRegionOperativa { get; set; }
        public string NombreTipoMetaCAN { get; set; }
        public string NombreRegionOperCAN { get; set; }
        public string CnStrServer { get; set; }
    }
}
