//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazSistema
{
    using System;
    using System.Collections.Generic;
    
    public partial class configcintillo
    {
        public int altocintillo { get; set; }
        public int colorfuente { get; set; }
        public int tamanofuente { get; set; }
        public int colorfondo { get; set; }
        public int velocidad { get; set; }
        public int vueltas { get; set; }
    }
}
