//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazSistema
{
    using System;
    using System.Collections.Generic;
    
    public partial class logprogramacion
    {
        public int Id { get; set; }
        public string rutavideo { get; set; }
        public int idvideo { get; set; }
        public int minutosmax { get; set; }
        public bool ejecucion { get; set; }
        public string error { get; set; }
        public float latitud { get; set; }
        public float longitud { get; set; }
        public string autobus { get; set; }
        public System.DateTime fechahora { get; set; }
        public int secuencia { get; set; }
        public int consecsecuencia { get; set; }
        public int idprogramacion { get; set; }
        public System.DateTime fechaprogramacion { get; set; }
    }
}
