//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazSistema
{
    using System;
    using System.Collections.Generic;
    
    public partial class puntosinteres
    {
        public long IdPunto { get; set; }
        public string Nombre { get; set; }
        public float Latitud { get; set; }
        public float Longitud { get; set; }
        public long MargenError { get; set; }
        public string Imagen { get; set; }
        public Nullable<long> punto_regreso { get; set; }
        public Nullable<int> tiempo_exposicion { get; set; }
        public string TipoPunto { get; set; }
        public string Sentido { get; set; }
        public Nullable<long> Hora_Inicio { get; set; }
        public Nullable<long> Hora_Fin { get; set; }
    }
}
