//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazSistema
{
    using System;
    using System.Collections.Generic;
    
    public partial class secuencias
    {
        public int idsecuencia { get; set; }
        public string region { get; set; }
        public string marca { get; set; }
        public string zona { get; set; }
        public string autobus { get; set; }
        public System.DateTime fechahorareal { get; set; }
        public sbyte ejecutada { get; set; }
    }
}
