//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazSistema
{
    using System;
    using System.Collections.Generic;
    
    public partial class sia_testigo_puntointeres
    {
        public long ID { get; set; }
        public long Autobus { get; set; }
        public long IDPunto { get; set; }
        public Nullable<System.DateTime> FechaDeteccion { get; set; }
        public Nullable<bool> Presentado { get; set; }
        public Nullable<System.DateTime> FechaPresentacion { get; set; }
    }
}
