//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazSistema
{
    using System;
    using System.Collections.Generic;
    
    public partial class smstouch
    {
        public long IdSmsTouch { get; set; }
        public Nullable<long> IdSms { get; set; }
        public Nullable<long> IdMarca { get; set; }
        public DateTime FechaSMS { get; set; }
        public Nullable<long> IdTipoSms { get; set; }
        public Nullable<long> IdEstatusAtendido { get; set; }
        public long IdDestinatario { get; set; }
        public string TextoSMS { get; set; }
        public Nullable<long> clvConductor { get; set; }
        public string NombreConductor { get; set; }
        public Nullable<long> IdPunto { get; set; }
    }
}
