//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazSistema
{
    using System;
    using System.Collections.Generic;
    
    public partial class vmd_testigo_video
    {
        public long ID { get; set; }
        public string VIDEO_CLAVE { get; set; }
        public string PAUTA_CLAVE { get; set; }
        public string AUTOBUS { get; set; }
        public System.DateTime FECHA_REPRODUCCION { get; set; }
        public bool COMPLETO { get; set; }
        public bool IMPACTOS { get; set; }
        public bool ACTIVO { get; set; }
    }
}
