//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazSistema
{
    using System;
    using System.Collections.Generic;
    
    public partial class vmd_dpauta_autorizada
    {
        public long ID { get; set; }
        public string PAUTA_CLAVE { get; set; }
        public long ORDEN { get; set; }
        public string VIDEO_CLAVE { get; set; }
        public string VIDEO_NOMBRE { get; set; }
        public string VIDEO_ARCHIVO { get; set; }
        public System.DateTime VIGENCIA_INICIO { get; set; }
        public System.DateTime VIGENCIA_FINAL { get; set; }
        public long DURACION { get; set; }
        public string CODEC_VIDEO { get; set; }
        public string CODEC_AUDIO { get; set; }
        public string FORMATO { get; set; }
        public bool SUBTITULOS { get; set; }
        public bool ACTIVO { get; set; }
        public string MD5 { get; set; }
    }
}
