//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazSistema
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class vmdEntities : DbContext
    {
        public vmdEntities()
            : base("name=vmdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<actividad> actividad { get; set; }
        public DbSet<archivos> archivos { get; set; }
        public DbSet<audiovmd> audiovmd { get; set; }
        public DbSet<autobuses> autobuses { get; set; }
        public DbSet<can_catbuses> can_catbuses { get; set; }
        public DbSet<can_catmetas> can_catmetas { get; set; }
        public DbSet<can_catmetasregionros> can_catmetasregionros { get; set; }
        public DbSet<can_contadores> can_contadores { get; set; }
        public DbSet<can_detsecuencia> can_detsecuencia { get; set; }
        public DbSet<can_logsincroniza> can_logsincroniza { get; set; }
        public DbSet<can_movtoscan> can_movtoscan { get; set; }
        public DbSet<can_operadores> can_operadores { get; set; }
        public DbSet<can_parametrosinicio> can_parametrosinicio { get; set; }
        public DbSet<can_poblaciones> can_poblaciones { get; set; }
        public DbSet<can_redes> can_redes { get; set; }
        public DbSet<can_referenciaregion> can_referenciaregion { get; set; }
        public DbSet<can_regsecuencia> can_regsecuencia { get; set; }
        public DbSet<can_secuencia> can_secuencia { get; set; }
        public DbSet<can_terminales> can_terminales { get; set; }
        public DbSet<can_versiones> can_versiones { get; set; }
        public DbSet<can_viajes> can_viajes { get; set; }
        public DbSet<can_zonasdescarga> can_zonasdescarga { get; set; }
        public DbSet<can_zonasdescarga2> can_zonasdescarga2 { get; set; }
        public DbSet<catclasif> catclasif { get; set; }
        public DbSet<catdestinatarios> catdestinatarios { get; set; }
        public DbSet<catpautas> catpautas { get; set; }
        public DbSet<configcintillo> configcintillo { get; set; }
        public DbSet<controlsecuencias> controlsecuencias { get; set; }
        public DbSet<cuadros> cuadros { get; set; }
        public DbSet<detsecuencias> detsecuencias { get; set; }
        public DbSet<logprogramacion> logprogramacion { get; set; }
        public DbSet<mensajes> mensajes { get; set; }
        public DbSet<mensajesrecibidos> mensajesrecibidos { get; set; }
        public DbSet<orden_descarga> orden_descarga { get; set; }
        public DbSet<plat_versiones> plat_versiones { get; set; }
        public DbSet<programacion> programacion { get; set; }
        public DbSet<random> random { get; set; }
        public DbSet<regiones> regiones { get; set; }
        public DbSet<secuencias> secuencias { get; set; }
        public DbSet<spot_parametros> spot_parametros { get; set; }
        public DbSet<vmd_dpauta_autorizada> vmd_dpauta_autorizada { get; set; }
        public DbSet<vmd_testigo_video> vmd_testigo_video { get; set; }
        public DbSet<zonas> zonas { get; set; }
        public DbSet<siaparametrosinicio> siaparametrosinicio { get; set; }
        public DbSet<parametros_vmd> parametros_vmd { get; set; }
        public DbSet<can_cattipometasregion> can_cattipometasregion { get; set; }
        public DbSet<can_zonasdescargainstancias> can_zonasdescargainstancias { get; set; }
    }
}
