//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazSistema.ModelosBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class actividad
    {
        public int idsecuencia { get; set; }
        public int idprogramacion { get; set; }
        public int consec { get; set; }
        public double posicion { get; set; }
        public double longitud { get; set; }
        public int consecsecuencia { get; set; }
        public int PosRandom { get; set; }
    }
}
