//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazSistema.ModelosBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class archivo_poi
    {
        public archivo_poi()
        {
            this.tipo_archivo_poi = new HashSet<tipo_archivo_poi>();
        }
    
        public long id_archivo_poi { get; set; }
        public long spotId { get; set; }
        public long spotArchivoId { get; set; }
        public string nombre { get; set; }
        public string url { get; set; }
        public bool activo { get; set; }
    
        public virtual detalles_poi detalles_poi { get; set; }
        public virtual ICollection<tipo_archivo_poi> tipo_archivo_poi { get; set; }
    }
}
