//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazSistema.ModelosBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class can2_geocerca
    {
        public int id { get; set; }
        public int geocercaListaId { get; set; }
        public string nombre { get; set; }
        public bool activo { get; set; }
        public string clave { get; set; }
        public System.DateTime fechaCreacion { get; set; }
    }
}
