//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazSistema.ModelosBD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CAN2Entities : DbContext
    {
        public CAN2Entities()
            : base("name=CAN2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<can2_config> can2_config { get; set; }
        public DbSet<can2_coordenadas> can2_coordenadas { get; set; }
        public DbSet<can2_geocerca> can2_geocerca { get; set; }
        public DbSet<can2_geocercaparametros> can2_geocercaparametros { get; set; }
        public DbSet<can2_parametros> can2_parametros { get; set; }
        public DbSet<can2_sync> can2_sync { get; set; }
        public DbSet<can2_testigo> can2_testigo { get; set; }
    }
}
