//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazSistema.ModelosBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class can2_geocercaparametros
    {
        public int id { get; set; }
        public int parametroId { get; set; }
        public string nombreParametro { get; set; }
        public double ValorParametro { get; set; }
        public double margenParametro { get; set; }
        public bool activo { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public System.DateTime fechaVigenciaInicio { get; set; }
        public System.DateTime fechaVigenciaFin { get; set; }
        public int orientacionInicial { get; set; }
        public int orientacionFinal { get; set; }
        public int geocercaId { get; set; }
    }
}
