//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazSistema.ModelosBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class can2_parametros
    {
        public int id { get; set; }
        public double valor_parametro { get; set; }
        public double valor_real { get; set; }
        public int geocerca_id { get; set; }
        public System.DateTime Fecha_Ini { get; set; }
        public double lat_Ini { get; set; }
        public double long_Ini { get; set; }
        public System.DateTime Fecha_Fin { get; set; }
        public double lat_Fin { get; set; }
        public double long_Fin { get; set; }
        public long operador { get; set; }
        public long Cambio_Manos { get; set; }
        public int parametroId { get; set; }
    }
}
