//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazSistema.ModelosBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class can_catmetas
    {
        public string Clasificacion { get; set; }
        public string Tipo { get; set; }
        public float Consejo { get; set; }
        public float Odometro { get; set; }
        public string Mes { get; set; }
        public int Year { get; set; }
        public string Region { get; set; }
        public long id { get; set; }
    }
}
