//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazSistema.ModelosBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class can_secuencia
    {
        public int idsecuencia { get; set; }
        public string idregion { get; set; }
        public string idmarca { get; set; }
        public string idzona { get; set; }
        public int servicio { get; set; }
        public string autobus { get; set; }
        public int version { get; set; }
        public Nullable<bool> confirmado { get; set; }
    }
}
