//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazSistema.ModelosBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class can_detsecuencia
    {
        public int idsecuencia { get; set; }
        public int orden { get; set; }
        public System.DateTime fecha { get; set; }
        public int numerotramo { get; set; }
        public int origen { get; set; }
        public int destino { get; set; }
        public Nullable<int> via { get; set; }
        public int oper1 { get; set; }
        public Nullable<int> oper2 { get; set; }
        public Nullable<bool> confirmado { get; set; }
        public int pobactual { get; set; }
    }
}
