//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazSistema.ModelosBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class can_catbuses
    {
        public string cvebus { get; set; }
        public string tipovehiculo { get; set; }
        public string matricula { get; set; }
        public string numeconomico { get; set; }
        public float rpmsmax { get; set; }
        public float velmax { get; set; }
        public int idmarca { get; set; }
    }
}
