//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazSistema.ModelosBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_media_disponible
    {
        public long id_cat_med_dis { get; set; }
        public string url { get; set; }
        public string nombre { get; set; }
        public long spotListaId { get; set; }
        public bool status { get; set; }
        public long spotArchivoId { get; set; }
        public string type { get; set; }
        public long tipo_spot { get; set; }
    }
}
