//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazSistema.ModelosBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_codigo
    {
        public long PK_ID { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public string Type_Action_Id { get; set; }
        public string Rango1 { get; set; }
        public string Rango2 { get; set; }
        public Nullable<long> Tiempo { get; set; }
        public string Type_Codigo_Id { get; set; }
        public string Pro_Tolerancia_Activo { get; set; }
        public long Pro_Tolerancia_Tiempo_Minimo { get; set; }
        public long Pro_Tolerancia_Tiempo_Maximo { get; set; }
        public long Pro_Tolerancia_Tolerancia { get; set; }
    }
}
