//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazSistema.ModelosBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class codigo
    {
        public long PK_ID { get; set; }
        public string Modulo { get; set; }
        public string Codigo1 { get; set; }
        public string Valor { get; set; }
        public long Type_Codigo_Id { get; set; }
        public string Autobus { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Lng { get; set; }
        public string NS { get; set; }
        public string WE { get; set; }
        public string Marca_Id { get; set; }
        public string Region_Id { get; set; }
        public string Region_Operativa_Id { get; set; }
        public Nullable<long> Clave_Operador { get; set; }
        public string Nombre_Operador { get; set; }
        public System.DateTime Fecha_Evento_Viaje { get; set; }
        public string Tipo_Viaje { get; set; }
        public long Status_Id { get; set; }
        public long Procesado { get; set; }
        public long Enviado { get; set; }
        public string Lote { get; set; }
        public string TipoLectura { get; set; }
        public string Contador { get; set; }
        public System.DateTime FechaHora_Inicio { get; set; }
        public System.DateTime FechaHora_Fin { get; set; }
        public string Protocolo { get; set; }
        public string Firmware { get; set; }
    }
}
