//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazSistema.ModelosBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class coordenadas_poi
    {
        public long coordenadas_id { get; set; }
        public long paradaId { get; set; }
        public long sequence { get; set; }
        public bool active { get; set; }
        public float latitud { get; set; }
        public float latitudCan { get; set; }
        public float longitud { get; set; }
        public float longitudCan { get; set; }
    }
}
