//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazSistema.ModelosBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuadros
    {
        public long Id { get; set; }
        public string Cve_pob { get; set; }
        public string Descripcion { get; set; }
        public float LatIni { get; set; }
        public float LonIni { get; set; }
        public float LatFin { get; set; }
        public float LonFin { get; set; }
        public string Tip_Cua { get; set; }
        public long Num_Con { get; set; }
    }
}
