//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazSistema.ModelosBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalles_poi
    {
        public detalles_poi()
        {
            this.archivo_poi = new HashSet<archivo_poi>();
            this.cat_poi = new HashSet<cat_poi>();
            this.testigo_poi = new HashSet<testigo_poi>();
        }
    
        public long spotId { get; set; }
        public long orientacionInicial { get; set; }
        public long orientacionFinal { get; set; }
        public string programacionHoraria { get; set; }
        public long duracion { get; set; }
        public long tiempoEspera { get; set; }
        public bool activo { get; set; }
        public System.DateTime fechaCreacion { get; set; }
    
        public virtual ICollection<archivo_poi> archivo_poi { get; set; }
        public virtual ICollection<cat_poi> cat_poi { get; set; }
        public virtual ICollection<testigo_poi> testigo_poi { get; set; }
    }
}
