//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazSistema.ModelosBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class lanzador_spot
    {
        public long id_lanzador_spot { get; set; }
        public long spotListaId { get; set; }
        public bool status { get; set; }
        public float latitud { get; set; }
        public float longitud { get; set; }
        public System.DateTime fecha_lanzamiento { get; set; }
        public long spotListaSecuencia { get; set; }
        public long spotArchivoId { get; set; }
    }
}
