//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazSistema.ModelosBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class parametrostelematics
    {
        public long PK_ID { get; set; }
        public string Servidor { get; set; }
        public string Puerto { get; set; }
        public string Tiempo_Envio { get; set; }
        public string Limite_Cola_Fallas { get; set; }
        public string WSSTREAM { get; set; }
        public long FactorAceleracion { get; set; }
        public long FactorDesaceleracion { get; set; }
        public string WSPACKAGE { get; set; }
        public long GuardarLote { get; set; }
        public string ServerPing { get; set; }
        public string UserWS { get; set; }
        public string PassWS { get; set; }
        public long CalculoAceleracion { get; set; }
        public long CalculoAcelerador { get; set; }
        public long PorcentajeAcelerador { get; set; }
        public string IdLAN { get; set; }
        public bool FiltroCodigos { get; set; }
        public bool FiltroFallas { get; set; }
        public string WSVersion { get; set; }
        public string WSCatalogo { get; set; }
        public bool LotePorStream { get; set; }
        public string WSPACKAGESTREAM { get; set; }
        public string TEMASTREAM { get; set; }
        public string Protocolo { get; set; }
        public string Firmware { get; set; }
    }
}
