//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazSistema.ModelosBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class plat_versiones
    {
        public long Id_Plat_Versiones { get; set; }
        public string Sistemas { get; set; }
        public string SubSistemas { get; set; }
        public string Modulo_Sis { get; set; }
        public string SubModulo_sis { get; set; }
        public string Versiones { get; set; }
    }
}
