//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazSistema.ModelosBD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class poiEntities : DbContext
    {
        public poiEntities()
            : base("name=poiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<archivo_poi> archivo_poi { get; set; }
        public DbSet<cat_poi> cat_poi { get; set; }
        public DbSet<coor_polygon> coor_polygon { get; set; }
        public DbSet<detalles_poi> detalles_poi { get; set; }
        public DbSet<parametros_poi> parametros_poi { get; set; }
        public DbSet<testigo_poi> testigo_poi { get; set; }
        public DbSet<tipo_archivo_poi> tipo_archivo_poi { get; set; }
    }
}
