//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazSistema.ModelosBD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class poiEntities : DbContext
    {
        public poiEntities()
            : base("name=poiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<spot_poi> spot_poi { get; set; }
        public DbSet<spotlista_poi> spotlista_poi { get; set; }
        public DbSet<cat_media_disponible> cat_media_disponible { get; set; }
        public DbSet<coordenadas_poi> coordenadas_poi { get; set; }
        public DbSet<lanzador_spot> lanzador_spot { get; set; }
        public DbSet<parada_poi> parada_poi { get; set; }
        public DbSet<parametros_poi> parametros_poi { get; set; }
        public DbSet<testigo_poi> testigo_poi { get; set; }
        public DbSet<spot_manual> spot_manual { get; set; }
    }
}
