//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazSistema.ModelosBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class programacion
    {
        public int Id { get; set; }
        public string Grupo { get; set; }
        public int Archivo { get; set; }
        public int Consec { get; set; }
        public sbyte TipoPunto { get; set; }
        public int IdPoblacion { get; set; }
        public bool Detener { get; set; }
        public bool TipoReprodRandom { get; set; }
        public System.DateTime TiempoRecorrido { get; set; }
        public System.DateTime TiempoSpots { get; set; }
    }
}
