//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazSistema.ModelosBD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SIAEntities : DbContext
    {
        public SIAEntities()
            : base("name=SIAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<catsms> catsms { get; set; }
        public DbSet<historialpublicidad> historialpublicidad { get; set; }
        public DbSet<listamensajes> listamensajes { get; set; }
        public DbSet<parametros> parametros { get; set; }
        public DbSet<puntosinteres> puntosinteres { get; set; }
        public DbSet<sia_historicoconductores> sia_historicoconductores { get; set; }
        public DbSet<sia_scripts> sia_scripts { get; set; }
        public DbSet<sia_testigo_puntointeres> sia_testigo_puntointeres { get; set; }
        public DbSet<siaparametrosinicio> siaparametrosinicio { get; set; }
        public DbSet<smstouch> smstouch { get; set; }
    }
}
