//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazSistema.ModelosBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class siaparametrosinicio
    {
        public long Tiempo_Localiza { get; set; }
        public long Tiempo_Disponibilidad { get; set; }
        public long IDVersion { get; set; }
        public string IDTarjetaLAN { get; set; }
        public string ServidorInternet { get; set; }
        public string ServidorSIA { get; set; }
        public long Tiempo_ParametrosExtendidos { get; set; }
        public long No_RegistrosHistoricos { get; set; }
        public long No_ParametrosExtendidos { get; set; }
        public long Tiempo_Actualizacion { get; set; }
        public bool Habilitar_Envio_ParametrosExtendidos { get; set; }
        public bool Habilitar_Envio_RegistrosHistoricos { get; set; }
        public long Tiempo_GuardadoHistoricos { get; set; }
        public string servidor_actualizacion { get; set; }
    }
}
