//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazSistema.ModelosBD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class telematicsEntities : DbContext
    {
        public telematicsEntities()
            : base("name=telematicsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<cat_codigo> cat_codigo { get; set; }
        public DbSet<cat_type_action> cat_type_action { get; set; }
        public DbSet<cat_type_codigo> cat_type_codigo { get; set; }
        public DbSet<codigo> codigo { get; set; }
        public DbSet<codigo_envio> codigo_envio { get; set; }
        public DbSet<version_tabla> version_tabla { get; set; }
        public DbSet<parametrostelematics> parametrostelematics { get; set; }
        public DbSet<falla_envio> falla_envio { get; set; }
    }
}
