//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazSistema.ModelosBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class testigo_poi
    {
        public long id_testigo_poi { get; set; }
        public string numeroEconomico { get; set; }
        public long spotId { get; set; }
        public System.DateTime fechaReproduccion { get; set; }
        public float latitud { get; set; }
        public float longitud { get; set; }
        public bool enviado { get; set; }
    
        public virtual detalles_poi detalles_poi { get; set; }
    }
}
