//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfazSistema.ModelosBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_archivo_poi
    {
        public long id_tipo_archivo_poi { get; set; }
        public long id_archivo_poi { get; set; }
        public long spotArchivoTipoId { get; set; }
        public string descripcion { get; set; }
        public bool activo { get; set; }
    
        public virtual archivo_poi archivo_poi { get; set; }
    }
}
